new commit

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -46,30 +46,35 @@ jobs:
         mvn versions:set -DnewVersion=$NEW_VERSION -f myapp/pom.xml
         mvn versions:commit -f myapp/pom.xml
 
-    - name: Build Docker Image
+    - name: Check version
       run: |
-        echo "Building Docker image with version ${{ env.new_version }}"
-        docker build -t matan2024/myapp:${{ env.new_version }} .
-        docker tag matan2024/myapp:${{ env.new_version }} matan2024/myapp:latest
+        echo "Current version: ${{ env.new_version }}"
 
-    - name: Log in to Docker Hub
-      run: |
-        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    - name: Push Docker Image to Docker Hub
-      run: |
-        set -e
-        docker push matan2024/myapp:${{ env.new_version }} || (echo "Retrying push..." && sleep 5 && docker push matan2024/myapp:${{ env.new_version }})
+    # - name: Build Docker Image
+    #   run: |
+    #     echo "Building Docker image with version ${{ env.new_version }}"
+    #     docker build -t matan2024/myapp:${{ env.new_version }} .
+    #     docker tag matan2024/myapp:${{ env.new_version }} matan2024/myapp:latest
 
-    - name: Install kubectl
-      run: |
-        sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+    # - name: Log in to Docker Hub
+    #   run: |
+    #     echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
-    - name: Install Helm
-      run: |
-        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+    # - name: Push Docker Image to Docker Hub
+    #   run: |
+    #     set -e
+    #     docker push matan2024/myapp:${{ env.new_version }} || (echo "Retrying push..." && sleep 5 && docker push matan2024/myapp:${{ env.new_version }})
 
-    - name: Deploy with Helm
-      run: |
-        helm upgrade --install myapp helm-chart/myapp --set image.tag=${{ env.new_version }}
+    # - name: Install kubectl
+    #   run: |
+    #     sudo curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+    #     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+
+    # - name: Install Helm
+    #   run: |
+    #     curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
+
+    # - name: Deploy with Helm
+    #   run: |
+    #     helm upgrade --install myapp helm-chart/myapp --set image.tag=${{ env.new_version }}
